### ISSUE TITLE
Dialog action color

### ISSUE THREAD

**Issue by fjfeijoo** [Ullfis/aurelia-mdc-bridge#10]
Please add "mdc-dialog__action" as an option for the action button in the dialog.

From https://material.io/components/web/catalog/dialogs/

**Comment by Ullfis** [comment]
Thank you :+1:

I added 2 attributes:

```html
accept-action=”true”
cancel-action=”true”
```

Both defaults to false.

**Comment by fjfeijoo** [comment]
That was quick!

Thanks a lot.
