### ISSUE TITLE
Clicking a list item highlights the item

### ISSUE THREAD

**Issue by djensen47** [Ullfis/aurelia-mdc-bridge#14]
If a list item does not have a click delegate nor wave, then an **_ugly_** focus box surrounds the list item. This only occurs in aurelia-mdc-bridge. With raw material-components-web, this does not occur.

![mdc-highligh-item-bug](https://user-images.githubusercontent.com/527865/30532771-dff50784-9c0a-11e7-82f4-af53f84238b9.png)

**Comment by Ullfis** [comment]
Error in `disabledChanged` added `tabindex="0"` to list-item.
