### ISSUE TITLE
Button with if.bind looses properties

### ISSUE THREAD

**Issue by fjfeijoo** [Ullfis/aurelia-mdc-bridge#17]
In a view where you hide/show buttons, they loose the properties:

```
<button mdc-button="raised: true; accent: true;" click.trigger="showButton = !showButton">Toggle</button>
<button if.bind="showButton" mdc-button="raised: true; accent: true;">Hi</button>
```

**Comment by Ullfis** [comment]
Button classes needed to be re-set during attached function.

Thank you for reporting it :+1:

**Comment by fjfeijoo** [comment]
Fab buttons with mdc-fab have the same issue.

Thanks!

**Comment by fjfeijoo** [comment]
There is still an issue, the fab buttons are loosing the inner span with the icon image, try this:

```
    <button mdc-fab="plain: true; mini: true; ripple: true;" click.trigger="showButton = !showButton">star</button>
    <button if.bind="showButton" mdc-fab="plain: true; mini: true; ripple: true;">star</button>
```

Thanks for your super quick fixes!

**Comment by Ullfis** [comment]
Thank you for finding these details
