### ISSUE TITLE
Feature: custom attribute for selected drawer items

### ISSUE THREAD

**Issue by djensen47** [Ullfis/aurelia-mdc-bridge#19]
As I'm building out a drawer, I thought it might be nice to have a custom attribute to specify which item in the drawer is selected. To take it a step further, it would be great if it could detect which drawer is being used and then use the appropriate class name for the selected item.

For now, I'll just use the `mdc-temporary-drawer--selected` class for the selected item.

Thanks!

**Comment by djensen47** [comment]
Actually, it turns out that I can't seem to apply the `mdc-temporary-drawer--selected` class.

I'm doing something like this but with no result:
```
class.bind="${row.isActive ? 'mdc-temporary-drawer--selected' : ''}"
```

**Comment by Ullfis** [comment]
Thank you :smile:
