### ISSUE TITLE
this.mdcTextfield.foundation_.adapter_.registerInputBlurHandler is not a function

### ISSUE THREAD

**Issue by djensen47** [Ullfis/aurelia-mdc-bridge#20]
There was a change in the mdc-textfield API causing the bridge to error on initialization:
```
Unhandled rejection TypeError: this.mdcTextfield.foundation_.adapter_.registerInputBlurHandler is not a function
    at MdcTextfield.attached 
```

It's listed here under breaking changes:
https://github.com/material-components/material-components-web/blob/master/CHANGELOG.md#0220-2017-10-02

I think the fix is fairly straightforward:
```
this.mdcTextfield.foundation_.adapter_.registerInputBlurHandler(this.onBlur.bind(this));
this.mdcTextfield.foundation_.adapter_.registerInputFocusHandler(this.onFocus.bind(this));        
```
becomes
```
this.mdcTextfield.foundation_.adapter_.registerInputInteractionHandler('blur', this.onBlur.bind(this));
this.mdcTextfield.foundation_.adapter_.registerInputInteractionHandler('focus', this.onFocus.bind(this));        
```

**Comment by djensen47** [comment]
Well, I'm trying to do a PR but after I clone the project and do `npm install` it just keeps spinning, not quite finishing. Is there a particular version of node I should be using?

**Comment by Ullfis** [comment]
Thank you :+1:

**Comment by djensen47** [comment]
No problem. I'm glad to pitch in. 

For future PRs, what workflow would you like me to follow?
