### ISSUE TITLE
material-components-web 0.21.0 breaking changes

### ISSUE THREAD

**Issue by djensen47** [Ullfis/aurelia-mdc-bridge#23]
These are the breaking changes for 0.21.0 I'm not sure if the snackbar code needs to be updated but the button and fab code definitely needs an update to remove `primary` and `accent`

- [x] snackbar: Removed the dependency of mdc-button from DOM structure of snackbar.
- [x] button: Remove support of mdc-button--primary and mdc-button--accent modifier classes. For custom and theme button implementation, use button mixins instead. See demos.scss for details.
- [x] fab: Removes mdc-fab--plain, please update your code to use mdc-fab-accessible mixin instead.

**Comment by Ullfis** [comment]
snackbar code also [updated](https://github.com/Ullfis/aurelia-mdc-bridge/commit/b5c351936c9da57be46c360d39cdc8969b393478)
