### ISSUE TITLE
Create pre-bundled packages for GistRun or CodeRun

### ISSUE THREAD

**Issue by djensen47** [Ullfis/aurelia-mdc-bridge#29]
When somebody finds a bug, it would be great to be able use a CodePen or a GistRun to show the bug. The way that aurelia-materialize-bridge does this is with pre-bundled assets in a separate repository.

Just a thought.

**Comment by Ullfis** [comment]
Try this one: [gist run](https://gist.run/?id=7e9a439b81c17ac94e40409cb1f4b14d)
