### ISSUE TITLE
Bug: mdc-select doesn't allow mouse input for new selections

### ISSUE THREAD

**Issue by djensen47** [Ullfis/aurelia-mdc-bridge#30]
1. Go to https://ullfis.github.io/aurelia-mdc-bridge/#/components/inputs/select-menus
2. Immediately select an item from one of the select menus
3. Select another item from one of the select menus

**Expected result:**
The second item selected is displayed

**Actual result:**
The first item is still displayed

**More Details**
Sometimes step 2 doesn't work

![mdc-select-bug](https://user-images.githubusercontent.com/527865/33053053-91ee2072-ce26-11e7-881d-78ddf057014d.gif)

**Comment by Ullfis** [comment]
Thank you for finding this. I see that if clicked outside the text (2 – USB) but on same line, the selection is made.

**Comment by djensen47** [comment]
Good catch. The keyboard shortcuts also work properly.

**Comment by Ullfis** [comment]
Trying with native component:

```jade
.mdc-select(ref="testElement" role="listbox" tabindex="0")
  span.mdc-select__selected-text Without span tag 1
  .mdc-simple-menu.mdc-select__menu
    ul.mdc-list.mdc-simple-menu__items
      li.mdc-list-item(role="option" id="span0" tabindex="0")
        span With span tag
      li.mdc-list-item(role="option" aria-selected id="span1" tabindex="0") Without span tag 1
      li.mdc-list-item(role="option" aria-selected id="span2" tabindex="0") Without span tag 2
```

```typescript
import { MDCSelect } from '@material/select';

private testElement: HTMLDivElement;

private attached() {
  const select = new MDCSelect(this.testElement);
}
```

Using span tag within a list-item does not work anymore.

**Comment by Ullfis** [comment]
The same is happening with Menus. pfffh..

**Comment by djensen47** [comment]
> Using span tag within a list-item does not work anymore.

😕 Is that a regression in material-components-web?

**Comment by Ullfis** [comment]
Same bug in Menus (https://ullfis.github.io/aurelia-mdc-bridge/#/components/menus)

**Comment by Ullfis** [comment]
When clicking one item a MouseEvent is raised and target of that event is compared to an item list. [code](https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu/simple/foundation.js#L370)

Item list is made of child items with class: `.mdc-list-item[role]` [code](https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu/simple/index.js#L78)

When one item contain tags, the tag is the target of the MouseEvent and is not found in that list.

**Comment by Ullfis** [comment]
I replaced the foundation adapter function `getIndexForEventTarget` for `mdc-simple-menu` and `mdc-select` so the closest parent element with class `mdc-list-item` is compared with the list.
