### ISSUE TITLE
mdc-grid-cell span can't be changed dynamically

### ISSUE THREAD

**Issue by fjfeijoo** [Ullfis/aurelia-mdc-bridge#35]
I would like to be able to dynamically change the span of a grid cell with something like:

```
<mdc-grid-cell span.bind="componentSpan">
</mdc-grid-cell>
```
But it only works the first time as the binding is a oneTime binding. Could this be changed?

@bindable({ defaultBindingMode: bindingMode.oneTime }) public span: IMdcGridCellNumber = null;

https://github.com/Ullfis/aurelia-mdc-bridge/blob/55b5955005b5b402182ae0adbe3cd36790e9262f/src/bridge/grid/grid-cell.ts#L14

Thanks!

**Comment by Opiskull** [comment]
I think it should work if you replace your span.bind with span.two-way

like the following

```
<mdc-grid-cell span.two-way="componentSpan">
</mdc-grid-cell>
```

**Comment by fjfeijoo** [comment]
No, it doesn't work with two-way as the component defines the oneTime binding internally.

**Comment by Opiskull** [comment]
ok. I looked at the component again and think it was never meant to be dynamic... The classes are only added in the attached call and that is only executed once. 

A possible workaround would be to remove and add the component again with an if.bind.


And the defaultBindingMode only overwrites what is used when you use `.bind`. It should be possible to overwrite it.

**Comment by Ullfis** [comment]
I changed the binding type to `toView`. And added classbinding to the properties. It have only been tested on `span` property but should work on `span-desktop`, `span-tablet`, `span-phone`, `align` and `order`.

I will update to latest Material Components before publishing.
