### ISSUE TITLE
Can I manually invalidate a text-field?

### ISSUE THREAD

**Issue by djensen47** [Ullfis/aurelia-mdc-bridge#38]
What I would like to do is invalidate a field after I receive a response from the server. For instance, on a login form, I would like to invalidate the field if the username or password is incorrect.

**Comment by Ullfis** [comment]
I can add a get/set valid function

```html
<mdc-text-field view-model.ref="textfieldModel"></mdc-text-field>
```

```typescript
this.textfieldModel.valid = !this.textfieldModel.valid;
```

**Comment by djensen47** [comment]
Yeah, that would be awesome.
