### ISSUE TITLE
Please Add Focus binding on textfields

### ISSUE THREAD

**Issue by raupes** [Ullfis/aurelia-mdc-bridge#4]
Congrats to this project!

Aurelia allows to [bind focus](http://blog.aurelia.io/2015/06/05/building-aurelias-focus-attribute/). Would you mind adding the possibility to textboxes.
`<input type="text" focus.bind="myHasFocus" />`
or with the bridge
`<mdc-textfield focus.bind="myHasFocus" />`

this would be really cool!
thank you

**Comment by Thanood** [comment]
Or even all events which don't bubble. I think for `input` this is only `blur` and `focus`.

**Comment by raupes** [comment]
Also it isn't possible to set the id of an input field - only the name.
So if i need to reference the id it is a problem.
thank you.

**Comment by Ullfis** [comment]
Thank you for the feedback :)

I tried in the past to create a bindable focus attribute inside a component without success. It didn’t track changes:

```javascript
@bindable({ defaultBindingMode: bindingMode.twoWay }) public focus = false;

focusChanged(newValue) {
  this.log.debug(‘focus changed’, newValue);
}
```

Nothing in the console...

So for now I'll just create a custom attribute `focused`:

```html
<mdc-textfield focused.bind=”focused” ...></mdc-textfield>
```

Also throwing events for focus and blur. 

```html
<mdc-textfield focus.delegate="onFocus()" blur.delegate="onBlur()" ...></mdc-textfield>
```

To get the input element you could do this:

```html
<mdc-textfield id=”mytextfield” ...></mdc-textfield>
```

```javascript
const inputElement = document.getElementById('mytextfield').getElementsByTagName('input')[0];
```

With `multiline` set to `true`, the tagName is `textarea`.

**Comment by Ullfis** [comment]
You can also focus the element from code:

```html
<mdc-textfield view-model.ref="textfieldModel" ...></mdc-textfield>
```

```javascript
import { MdcTextfield } from 'aurelia-mdc-bridge';
private textfieldModel: MdcTextfield;

...
this.textfieldModel.focus();

or
this.textfieldModel.focused = true;
```

To get the input element you can use:

```javascript
const inputElement = this.textfieldModel.getNativeInput();
```

From foundation documentation:

> getNativeInput() => {value: string, disabled: boolean, badInput: boolean, checkValidity: () => boolean}

>Returns an object representing the native text input element, with a similar API shape. The object returned should include the value, disabled and badInput properties, as well as the checkValidity() function. We never alter the value within our code, however we do update the disabled property, so if you choose to duck-type the return value for this method in your implementation it’s important to keep this in mind. Also note that this method can return null, which the foundation will handle gracefully.

Hope this can help :)
