### ISSUE TITLE
Avatar list example 1 doesn't seem to work

### ISSUE THREAD

**Issue by djensen47** [Ullfis/aurelia-mdc-bridge#7]
In the component docs there's an example of using an avatar list:

```
  <mdc-list-item>
    <span slot="start" class="list-avatar1"></span>
    <span slot="text">List item 1</span>
    <span slot="secondary">Line 2 secondary text</span>
  </mdc-list-item>
```

When it wasn't working for me, I went to inspect the code. 

It appears that nothing happens when a start slot has no child nodes:
https://github.com/Ullfis/aurelia-mdc-bridge/blob/master/src/bridge/list/create-components.ts#L108

But the example in the docs worked, so I looked the docs code. It turns out there's an error in the docs code. It should be:

```
  <mdc-list-item>
    <span slot="start"><div class="list-avatar1"></div></span>
    <span slot="text">List item 1</span>
    <span slot="secondary">Line 2 secondary text</span>
  </mdc-list-item>
```

**Comment by Ullfis** [comment]
Thank you for this observation and correction :+1:
